#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/work/emddi/ssh/ -type f | fzf-tmux -p --reverse)
fi

if [[ -z $selected ]]; then
    exit 0
fi

echo "---------- Executing: $selected -------------"
$selected
